apiVersion: apps/v1
kind: Deployment
metadata:
  name: key-value-store
  labels:
    app: key-value-store
spec:
  replicas: 1
  selector:
    matchLabels:
      service: key-value-store
  template:
    metadata:
      labels:
        app: key-value-store
        service: key-value-store
    spec:
      containers:
        - name: webapi
          image: arnoldacho.azurecr.io/key-value-store:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80

---
apiVersion: v1
kind: Service
metadata:
  name: key-value-store
  labels:
    app: key-value-store
    service: key-value-store
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: key-value-store